# Base image.
FROM node:22.4.1-alpine

# Set evironment variables.
# Set evironment variables.
ENV LANG=C.UTF-8

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./src/package.json .

# Install packages.
RUN npm install

# Copy directory.
COPY ./src .

# Document exposed port.
EXPOSE 3000

# Start app.
CMD ["npm", "run", "start"]